apiVersion: 1

deleteDatasources:
  - name: Prometheus
    orgId: 1

datasources:

  - name: Prometheus
    type: prometheus
    uid: aeromed-prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      httpMethod: POST
      timeInterval: "15s"
      queryTimeout: "60s"
      prometheusType: Prometheus
      prometheusVersion: "2.47.0"
      manageAlerts: true
      alertmanagerUid: aeromed-alertmanager

  - name: AlertManager
    type: alertmanager
    uid: aeromed-alertmanager
    access: proxy
    orgId: 1
    url: http://alertmanager:9093
    isDefault: false
    editable: false
    jsonData:
      handleGrafanaManagedAlerts: false
      implementation: prometheus
